version: '3'

tasks:
  gen-ast:
    dir: codegen
    cmds:
      - cargo run < ../syntax.ungram | zig fmt --stdin > ../src/ast.zig
    generates:
      - src/ast.zig
  run:
    cmds:
      - zig run src/main.zig
  test:
    cmds:
      - zig test src/main.zig
