[package]
name = "mir"
version = "0.0.0"
edition = "2021"

[dependencies]
hir = { version = "0.0.0", path = "../hir" }
syntax = { version = "0.0.0", path = "../syntax" }

[dev-dependencies]
expect-test = "1.4.1"
